### ISSUE TITLE
userDashboard

### ISSUE THREAD

**Issue by maxrandrade** [MRAndrade/techdb-design#18]
- [x] Criar o searchContainer
- [x] Criar o FAB

**Comment by maxrandrade** [comment]
@rafaelcorreiapoli Finalizado e commitado. To deixando em aberto até você checar aí se tá tudo ok.

Eu tinha configurado pra que o Floating Action Button ficasse dentro do searchContainer, mas depois eu pensei que se vai ter infinite scrolling, então é melhor que o botão fique fixo na tela. Assim o usuário consegue clicar nele independente da posição que a tela esteja. Além disso, outro problema de o botão não ficar fixo na tela é se o usuário rodar muito pra baixo a tabela e depois subir a tela. Se ele quiser clicar no botão, vai ter que rodar toda a tela até embaixo de novo. Então fiz dessa maneira.

**Comment by rafaelcorreiapoli** [comment]
Sim, a idéia do FAB (floating action button) é ele ficar fixo na tela e não dentro de algum componente da tela
Vou ver e já respondo
