### ISSUE TITLE
searchContainer

### ISSUE THREAD

**Issue by maxrandrade** [MRAndrade/techdb-design#2]
- [x] Criar searchBar
- [x] Criar searchToggle
- [x] Criar Table View
- [x] Criar Grid View

@rafaelcorreiapoli você faz alguma ideia de como funcionam essas Data Tables do inspinia? Porque eu ia começar a estruturar uma aqui pro list-view do searchContainer, mas to vendo que cada elemento da tabela tem uma penca de classes e provavelmente isso é de plugin. Dá um salve aí.

**Comment by rafaelcorreiapoli** [comment]
O que tá descrito lá, com datatables e tal também caiu pro primeiro milestone

**Comment by maxrandrade** [comment]
'Caiu' pro primeiro milestone? Não entendi. Ou ce quis dizer que saiu?

**Comment by rafaelcorreiapoli** [comment]
Hahaha foi mal a ambiguidade. Quero dizer que aquela listview como projetamos não vai mais existir no primeiro milestone, ficou pra depois. O que iremos fazer agora é utilizar uma tabela simples do bootstrap

**Comment by maxrandrade** [comment]
@rafaelcorreiapoli Finalizei o searchContainer. Dentro do html dele tem um template do tableView, outro do gridView e outro pro floatActionButton. Eu vou commitar com o searchContainer no griedView, mas tão todos os componentes lá disponíveis pra você montar o toggle e tudo o mais.

**Comment by maxrandrade** [comment]
@rafaelcorreiapoli Acabei de reorganizar o searchContainer. Vou explicar abaixo como que tá a estrutura agora e as principais modificações que eu fiz:

1 - Excluí o defaultMinorComponents. A ideia no começo foi boa, mas na prática mais bagunçou do que facilitou. Quase todos os componentes já estão criados e no final das contas essa tela não ajudou em nada, só tinha um exemplo de Panel e de Searchbar, então eu excluí.

2 - A barra de busca, os botões toggle e o table/gridView estão agora todos dentro do searchContainer.html . Abaixo vou citar o nome de cada template, só pra deixar esclarecido:
- floatingActionButton -> template do botão flutuante. Ele está sendo chamado dentro da tableView.
- tableActionButtons -> template dos botões de ação dentro da tableView.
- gridView -> template da opção de visualização em grid.
- tableView -> template da opção de visualização em tabela.
- searchSource -> template somente da barra de busca com o metadata embaixo devidamente alinhado na direita.
- searchSourceSearchToggle -> searchSource + botões de opção de visualização
- searchContainer -> template completo. Ibox que contém um searchSourceSearchToggle + uma tableView OU gridView.

3 - Excluí o searchSource.import.less, porque como eu disse, todos os componentes que dizem respeito ao conteúdo de busca agora estão dentro do searchContainer.html. Então a própria configuração que tinha dentro do searchSource.import.less tá dentro do searchContainer.import.less agora.

4 - Eu reformei o searchSource que você tinha criado com o metadata. Ele tá bem mais simplificado, pra falar a verdade, e está posicionado devidamente, sem a necessidade de utilizar rows, colunas etc.

Bom, basicamente é isso bro. Espero que tenha conseguido ser bem claro na explicação de tudo.

**Comment by rafaelcorreiapoli** [comment]
Boa Max, mas mano, eu já criei uma organização minha aqui a partir de todo html e css que vc me mandou (e já ta bom e funcionando)
Por isso to falando pra vc não esquentar tanto com isso, você querer dixavar tanto os componentes assim acaba complicando o meu trampo pq eu tenho que ficar caçando as coisas, por mais organizado que esteja
Quando se trata de grandes componentes/telas (como orgEntry, orgAboutBox, etc) aí a divisão tem que acontecer, e ela é óbvia
Agora quando são umas coisas mais complexas, compostas por uma caralhada de componentezinho, é mais fácil pra mim e pra você se vc simplesmente construir todo html num lugar só, e ai eu só vou extraindo e criando os templates aqui da forma que melhor se encaixe com o resto da estrutura do programa, até pq muita coisa eu mudo na hora (em relação à organização de templates) pq percebo na hora o que faz mais sentido ou não

**Comment by rafaelcorreiapoli** [comment]
De qualquer maneira eu ainda não terminei todos os templates relacionados à essa parte, então essa organização que você fez agora com certeza vai me ajudar, pq está mais clara que a anterior
