### ISSUE TITLE
attachmentDashboard

### ISSUE THREAD

**Issue by maxrandrade** [MRAndrade/techdb-design#21]
- [x] Criar searchAttachmentsContainer
- [x] Criar recentUpdates

**Comment by maxrandrade** [comment]
![](https://cloud.githubusercontent.com/assets/4376835/12306200/b29ceb0e-ba1f-11e5-8a94-69a7f9a51af0.png)

@rafaelcorreiapoli eu tava pensando aqui e o attachmentDashboard tem praticamente os mesmos componentes do searchAttachmentsContainer. Me parece que o searchAttachmentsContainer é na verdade só esse componente da esquerda e que o attachmentDashboard seria essa tela completa, não? Esse wireframe tá sendo usado pra ilustrar o searchAttachmentsContainer, não o dashboard completo, então tá meio confuso.

**Comment by rafaelcorreiapoli** [comment]
Mano, ta confuso pra caralho essa porra e eu peço desculpas por isso haha
no cenário atual, o attachmentDashboard pode ser entendido como uma composição do searchAttachmentsContainer um um recentUpdates
