### ISSUE TITLE
Ajustando mobile

### ISSUE THREAD

**Issue by maxrandrade** [MRAndrade/techdb-design#23]
@rafaelcorreiapoli O que você acha de configurar media querys pro mobile? Eu acho que só ajeitar margin e padding não vai salvar o layout. Acho que precisa também mexer no tamanho de alguns elementos pra quando tiver numa tela pequena, etc. Eu pensei em fazer a configuração media query dentro do .less de cada respectivo elemento, assim fica fácil de achar as configurações.

Além disso, tava pensando em transformar em variáveis os pontos de min-width e max-width das media querys. Assim a gente consegue facilmente alterar os locais de breakpoint, caso necessário (eu particularmente acho uma merda os breakpoints do bootstrap).

**Comment by rafaelcorreiapoli** [comment]
Acho que o primeiro passo é realmente ajustar as margins e os paddings quando tá no mobile. Feito isso, o que ainda continuar ruim a gente tenta resolver usando o grid do bootstrap (pra separar os elementos em diversas linhas por exemplo), o que mesmo assim estiver ruim ainda a gente aplica media queries e modifica os elemnetos em si
