### ISSUE TITLE
searchAttachmentsContainer

### ISSUE THREAD

**Issue by maxrandrade** [MRAndrade/techdb-design#3]
- [x] Montar grid que disponha um attachmentAboutBox e um searchContainer com attachmentThumbnails dentro.

@rafaelcorreiapoli Preciso de umas informações sobre esse componente. Eu já tenho tudo montado pra ele, só precisa estruturar.

O wireframe não fica tão legal, na prática. Vou citar os pontos que tão em conflito:
1. Aquelas abas de Information/Recent Updates (vou chamar de changeTab), se ficarem coladas com o attachmentAboutBox que tá embaixo, fica realmente estranho. No próprio wireframe dá pra ver que attachmentAboutBox fica desalinhado em relação aos attachmentThumbnail na esquerda. Além disso a borda no topo dele fica colada com os botões em cima, é feio, pra ser sincero.
2. Levando em consideração o que eu citei no 1, eu criei uma certa margem pra ser aplicada no search e nesse changeTab. Na prática eu não posso simplesmente colocar um box em volta dos dois e dar uma margem, porque isso só funcionaria devidamente se os dois estivessem na mesma row, etc. Não vou entrar muito em detalhes, mas fato é que eu resolvi isso criando um box pros dois, que tem uma certa margem, assim eles ficam sempre alinhados um em relação ao outro, independente do grid ou de qualquer outra coisa.
3. Não sei se é planejado que todos esses componentes fiquem dentro de um ibox, pra ter um fundo branco.  Eu sinceramente testei e não achei muito legal o resultado também. Porque fica um ibox dentro de outro ibox, etc, não é agradável. Então eu também tentei colocar dentro de um ibox só a parte da esquerda (a searchbar e os resultados), não sei se foi a melhor coisa a ser feita também.

Conclusão: nenhuma solução tá parecendo tão agradável, então precisamos decidir como que isso vai ficar montado exatamente: com ou sem fundo branco, changeTab colada no attachmentAboutBox ou não.

**Comment by maxrandrade** [comment]
Vou commitar montado da maneira que eu achei mais aceitável.

**Comment by rafaelcorreiapoli** [comment]
Cara, esse componente não tem no primeiro milestone =(
Mas já respondo suas dúvidas

**Comment by maxrandrade** [comment]
Ele sempre esteve marcado lá no 1º Milestone.

https://github.com/envisioning/techdb/issues/50

**Comment by rafaelcorreiapoli** [comment]
Sim, no nosso combinado você teria que fazer todas as issues do primeiro milestone, então de qualquer jeito eu gostaria que você me entregasse essa tela, mesmo que não formos usar agora.. meu aviso foi mais pra você não encanar tanto com ela agora

Sim, essa tela tá tosca, acho que precias de uma reformulação
realmente um box dentro do outro acho que fica zuado também
rola de você montar umas idéias e me mandar um print ou mesmo usar o Balsamiq? é dificil imaginar só lendo

**Comment by maxrandrade** [comment]
Acho que ficaria melhor assim:

![b29ceb0e-ba1f-11e5-8a94-69a7f9a51af0](https://cloud.githubusercontent.com/assets/12742302/12698362/e6892530-c781-11e5-8f94-48d245abe30f.png)

O attachmentAboutBox na esquerda segue o padrão das outras telas, recentUpdates aparecendo embaixo, ao inves de ser em abas. A unica coisa que precisa ver como fica melhor é o searchAttachmentContainer em si, porque não sei se infinite scrolling fica bom com essa disposição.

**Comment by rafaelcorreiapoli** [comment]
Ta ficando bom!
mas a parte do searchContainer coloca dentro de um box, assim mantemos o padrão de tudo dentro de boxes
e aí os resultados a gente faz com infinite scrolling mas dentro de uma perfectScrollbar pra não alterar o Height
http://noraesae.github.io/perfect-scrollbar/
