### ISSUE TITLE
elasticSearch

### ISSUE THREAD

**Issue by maxrandrade** [MRAndrade/techdb-design#4]
@rafaelcorreiapoli Como você disse pra mim um tempo atrás, o elasticSearch não vai ter todas as telas que tão desenhadas lá na issue do projeto oficial.

É só mesmo uma tela com ícones, caixa de texto pra busca e os resultados embaixo?

Quando clicar em cada ícone não vai mais aparecer uma janela pra configurar os parâmetros de busca?
(Readiness, Impact, In Collection, no technology search por exemplo)

**Comment by rafaelcorreiapoli** [comment]
![elastic search](https://cloud.githubusercontent.com/assets/12840136/12693663/657b8cb0-c6f7-11e5-8838-4836daeb8843.png)

Correto, não haverão mais todas as telas descritas lá
a gente simplificou bastante e na verdade vai ter só uma caixa de texto de busca e os resultados vão conter resultados de todas as entidades (organizations, technologies, etc...). não vai mais ser separado

**Comment by rafaelcorreiapoli** [comment]
Essa é a estrutura basica que eu criei pra deixar ela funcional.. entao basicamente são os 4 icones ali em cima, cada um representando uma entidade
uma caixa de texto
um icone de status(repare no icone que tem ao lado da caixa de texto, o checkmark indica que já terminou de carregar. podia ser um icone de error ou um fa-spinner fa-spin enquanto tiver carregando
tem também a METADATA da busca (que é o took=quanto tempo levou a busca e o total=quantos resultados voltaram)
dai tem os resultados em si que na verdade vão ser mostrados usando briefcards para este primeiro milestone

**Comment by rafaelcorreiapoli** [comment]
Ao clicar no botão da entidade ela fica "active", mas de boa isso eu já programei. usei as classes default e success do bootstrap
Outra coisa, não se prenda à disposição dos elementos que eu fiz ai, eu fiz de qqr jeito pra deixar funcional. a idéia é mesmo que vc crie e desenvolva algo bonito haha
