### ISSUE TITLE
manageUserRole

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [MRAndrade/techdb-design#6]
- [x] Refazer

**Comment by maxrandrade** [comment]
@rafaelcorreiapoli Tenho em mente remontar esses dois modais com a mesma identidade visual dos modais que você criou. Você estabeleceu alguma width pro modais que você fez? Porque vi que eles são um pouco mais estreitos, diferente das classes pré-estabelecidas disponíveis pelo inspinia.

**Comment by rafaelcorreiapoli** [comment]
Eu usei as classes la do inspinia mesmo.
Eu substitui o grid pela table e deu caca com os alinhamentos.. Alem disso, os botoes das actions tem que ter um padrao ao longo do App, no caso dessa tela seria legal ter icones representando cada role, eu jah refiz praticamente tudo aqui desse componente, ficou faltando soh o alinhamento vertical nas td's

**Comment by maxrandrade** [comment]
Deu caca porque cada elemento ali era uma coluna dentro de uma row e cada coluna tinha uma configuração flex, então só de transferir de grid pra table não ia rolar, por isso disse que tinha de fato de refazer, ao inves de só substituir.

**Comment by maxrandrade** [comment]
@rafaelcorreiapoli Finalizado e commitado. To deixando em aberto até você checar aí se tá tudo ok.
